version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing dependencies..."
      - pip install databricks-cli
  build:
    commands:
      - echo "Running deployment script..."
      - chmod +x deploy.sh
      - ./deploy.sh
  post_build:
    commands:
      - echo "Build and deployment completed."
artifacts:
  files:
    - "**/*"
