version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing Databricks CLI..."
      - pip install databricks-cli
      - curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | sh
  pre_build:
    commands:
      - echo "Configuring Databricks CLI..."
      - ls -ld ~
      - chmod u+w ~
      - touch ~/.databrickscfg
      - chmod 600 ~/.databrickscfg
      - echo "[DEFAULT]" > ~/.databrickscfg 
      - echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg
      - echo "host = https://dbc-bc2256ee-0075.cloud.databricks.com" >> ~/.databrickscfg
      - echo "Databricks CLI configured successfully."
  build:
    commands:
      - echo "Starting Databricks deployment using databricks.yml..."
      - databricks bundle deploy --config-file databricks.yml
      - echo "Deployment completed successfully!"
    post_build:
    commands:
      - echo "Deployment completed successfully."  

artifacts:
  files:
    - "**/*"
